[project]
name = "odoo-addons-oca-hr-holidays"
version = "19.0.20260612.0"
dependencies = [
    "odoo-addon-hr_holidays_leave_report_calendar_type==19.0.*",
    "odoo-addon-hr_holidays_natural_period==19.0.*",
    "odoo-addon-hr_holidays_public==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
